// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// engine.cpp
std::string pslr_engine_id();
extern "C" SEXP _pslr_pslr_engine_id() {
  BEGIN_CPP11
    return cpp11::as_sexp(pslr_engine_id());
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_pslr_pslr_engine_id", (DL_FUNC) &_pslr_pslr_engine_id, 0},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_pslr(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
